### ISSUE TITLE
gettxout not enabled

### ISSUE THREAD

**Issue by opreturn-net** [nformant1/DogecoinAPI#1]
##Here's the code for gettxout to work with both txid and n variables:

```
@app.get("/api/dogecoin/gettxout/{txid}/{n}")
def get_txout(txid: str, n: int):
    """
    Returns details about an unspent transaction output.
    """
    rpc = RPC_Connection(doge_user, doge_password, doge_host, doge_port)
    data = {}
    try:
        data = rpc.command("gettxout", params=[txid, n])
        return data
    except Exception as e:
        raise HTTPException(status_code=418, detail="Something went wrong")
```

**Comment by nformant1** [comment]
Thx, this was added within your PR: https://github.com/nformant1/DogecoinAPI/pull/2/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R234

...so imho this can be closed. Thanks again for your contribution to this API 👍
